"""dodat zip u Kupac

Revision ID: 1955fc32d624
Revises: 5cca2a4072d1
Create Date: 2025-05-11 21:36:18.618255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1955fc32d624'
down_revision = '5cca2a4072d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kupci', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kupci', schema=None) as batch_op:
        batch_op.drop_column('zip')

    # ### end Alembic commands ###
