"""status vs is_paid u PaymentSlip

Revision ID: 2cdbc65b4ef7
Revises: 521225017d8e
Create Date: 2025-05-20 22:15:31.455880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cdbc65b4ef7'
down_revision = '521225017d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_slips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_slips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
