"""Dodato note u PaymentItem

Revision ID: 36b0572ca62a
Revises: 2cdbc65b4ef7
Create Date: 2025-06-04 15:25:02.078512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b0572ca62a'
down_revision = '2cdbc65b4ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_items', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
