"""dodata kolona amount_paid u PaymentSlip

Revision ID: 521225017d8e
Revises: cf426db3e17a
Create Date: 2025-05-20 21:45:35.256460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521225017d8e'
down_revision = 'cf426db3e17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_slips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_slips', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
