"""inicijalna migraija

Revision ID: 5cca2a4072d1
Revises: 
Create Date: 2025-05-11 21:16:52.499851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cca2a4072d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kupci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime_prezime', sa.String(length=120), nullable=False),
    sa.Column('adresa', sa.String(length=200), nullable=False),
    sa.Column('mesto', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('način_preuzimanja', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uplatnice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('ukupan_iznos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('svrha_uplate', sa.String(length=100), nullable=True),
    sa.Column('račun_primaoca', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=10), nullable=True),
    sa.Column('šifra_plaćanja', sa.String(length=20), nullable=True),
    sa.Column('valuta', sa.String(length=5), nullable=True),
    sa.Column('kupac_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kupac_id'], ['kupci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stavke_karata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv_karte', sa.String(length=20), nullable=False),
    sa.Column('količina', sa.Integer(), nullable=False),
    sa.Column('cena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('uplatnica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uplatnica_id'], ['uplatnice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stavke_karata')
    op.drop_table('uplatnice')
    op.drop_table('kupci')
    # ### end Alembic commands ###
