"""Dodata tabela unallocated_payments za neraspoređene uplate

Revision ID: a1f2c3d4e5f6
Revises: 8b63c3b9770b
Create Date: 2026-06-21 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f2c3d4e5f6'
down_revision = '8b63c3b9770b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'unallocated_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('payment_id', sa.Integer(), nullable=False),
        sa.Column('payer_name', sa.String(length=200), nullable=True),
        sa.Column('reference_number', sa.String(length=50), nullable=True),
        sa.Column('reference_model', sa.String(length=10), nullable=True),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('purpose', sa.String(length=300), nullable=True),
        sa.Column('reason', sa.String(length=100), nullable=False),
        sa.Column('is_resolved', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unallocated_payments')
    # ### end Alembic commands ###
