"""phone dodato u Customer

Revision ID: cf426db3e17a
Revises: 3d6a22cfcdb4
Create Date: 2025-05-20 20:42:12.714924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf426db3e17a'
down_revision = '3d6a22cfcdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
